## Introduction

The Spaceship Titanic is a Machine Learning competition currently running on Kaggle with the participation of more than 2,000 teams.

As final project in this module, we will run a small competition using a smaller dataset, and you will need to use GP or GE to evolve a solution.

## Description

Welcome to the year 2912, where your data science skills are needed to solve a cosmic mystery. We've received a transmission from four lightyears away and things aren't looking good.

The Spaceship Titanic was an interstellar passenger liner launched a month ago. With almost 13,000 passengers on board, the vessel set out on its maiden voyage transporting emigrants from our solar system to three newly habitable exoplanets orbiting nearby stars.

While rounding Alpha Centauri en route to its first destination—the torrid 55 Cancri E—the unwary Spaceship Titanic collided with a spacetime anomaly hidden within a dust cloud. Sadly, it met a similar fate as its namesake from 1000 years before. Though the ship stayed intact, almost half of the passengers were transported to an alternate dimension!

To help rescue crews and retrieve the lost passengers, you are challenged to predict which passengers were transported by the anomaly using records recovered from the spaceship’s damaged computer system.

Help save them and change history!

In [1]:
# Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Dataset

The dataset provides 12 input variables that are a mixture of categorical, ordinal, boolean and numerical data types:

1. PassengerId
2. HomePlanet
3. CryoSleep
4. Destination
5. Age
6. VIP
7. RoomService
8. FoodCourt
9. ShoppingMall
10. Spa
11. VRDeck
12. Name

This is a binary classification problem where the task is to predict whether a passenger was transported to an alternate dimension.

### Load the dataset

In [2]:
# Suppressing Warnings:
import warnings
warnings.filterwarnings("ignore")

In [3]:
## mount your Google drive
# 1) click on the link
# 2) sign in
# 3) copy the provided code
# 4) paste it in the text box bellow
# 5) click the folder icon at the right
# 6) verify your drive is mounted

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

Clone the GRAPE repository at first because the dataset to be used is already there.

In [4]:
import os
# Get the library from our BDS research Group
# copy the path from your drive
PATH = '/content/drive/u/1/folders/1--2pl_taR8wZpcFAvbQNWaQen1afSZQF'

# check if 'grape' already exists
if os.path.exists(PATH):
    print('grape directory already exists')
else:
    %cd /content/drive/MyDrive/
    !git clone https://github.com/UL-BDS/grape.git 
    print('Cloning grape in your Drive')

# change directory to 'grape'
%cd /content/drive/MyDrive/grape/

/content/drive/MyDrive
fatal: destination path 'grape' already exists and is not an empty directory.
Cloning grape in your Drive
/content/drive/MyDrive/grape

### Train set

In [5]:
train_file = 'datasets/spaceshipTitanic_train.csv'

In [6]:
# load train set
import pandas as pd
df_train = pd.read_csv('/content/drive/MyDrive/grape/datasets/spaceshipTitanic_train.csv')
df_train.head()

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0,Earth,False,55 Cancri e,22,False,0,833,381,0,12,Miranda Pratt,True
1,1,Mars,True,TRAPPIST-1e,61,False,0,0,0,0,0,Isaac Werner,True
2,2,Mars,True,TRAPPIST-1e,5,False,0,0,0,0,0,Elisha Rosario,True
3,3,Earth,False,55 Cancri e,14,False,653,0,4,0,0,Deshawn Hall,False
4,4,Earth,False,PSO J318.5-22,2,False,0,0,0,0,0,Justice Archer,True

In [7]:
df_train.describe()

,PassengerId,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,999.500000,28.555500,213.460500,497.902500,166.237000,342.252000,269.211000
std,577.494589,14.629112,615.762402,1763.257082,509.568841,1236.474773,1021.074852
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,499.750000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,999.500000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1499.250000,37.000000,32.000000,61.250000,23.000000,67.250000,37.000000
max,1999.000000,79.000000,6899.000000,27723.000000,10424.000000,18572.000000,14485.000000

In [8]:
X_train = df_train.copy()
# warning: cannot drop it more than once
X_train.drop(['Transported'], axis=1, inplace=True)

In [9]:
# class labels
import numpy as np
l, _ = X_train.shape

y_train = np.zeros([l,], dtype=bool)

for i in range(l):
  y_train[i] = df_train['Transported'].iloc[i]

In [10]:
#y_train.head()
print(y_train[0:5])

[ True  True  True False  True]

### Test set

In [11]:
test_file = 'datasets/spaceshipTitanic_test.csv'

In [12]:
# load test set
df_test = pd.read_csv('/content/drive/MyDrive/grape/datasets/spaceshipTitanic_test.csv')
df_test.head()

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,2000,Mars,False,TRAPPIST-1e,54,False,676,0,231,379,0,Dawson Knox
1,2001,Mars,False,TRAPPIST-1e,43,False,336,11,796,15,0,Jaylee Navarro
2,2002,Europa,False,55 Cancri e,33,False,77,2381,0,3656,150,Dario Hart
3,2003,Earth,True,55 Cancri e,30,False,0,0,0,0,0,Alden Parker
4,2004,Europa,False,TRAPPIST-1e,31,False,0,53,0,2963,1017,Gina Frank

In [13]:
df_test.describe()

,PassengerId,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,4923.000000,4923.000000,4923.000000,4923.000000,4923.000000,4923.000000,4923.000000
mean,4461.000000,29.028235,231.206175,473.335568,184.646354,308.407678,317.807434
std,1421.292018,14.466997,696.138873,1634.705363,677.528376,1126.346091,1164.989135
min,2000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3230.500000,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4461.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5691.500000,38.000000,59.000000,84.000000,31.000000,63.000000,59.500000
max,6922.000000,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,20336.000000

In [14]:
df_test

,PassengerId,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,2000,Mars,False,TRAPPIST-1e,54,False,676,0,231,379,0,Dawson Knox
1,2001,Mars,False,TRAPPIST-1e,43,False,336,11,796,15,0,Jaylee Navarro
2,2002,Europa,False,55 Cancri e,33,False,77,2381,0,3656,150,Dario Hart
3,2003,Earth,True,55 Cancri e,30,False,0,0,0,0,0,Alden Parker
4,2004,Europa,False,TRAPPIST-1e,31,False,0,53,0,2963,1017,Gina Frank
...,...,...,...,...,...,...,...,...,...,...,...,...
4918,6918,Earth,True,PSO J318.5-22,46,False,0,0,0,0,0,Lamar Knight
4919,6919,Europa,True,TRAPPIST-1e,15,False,0,0,0,0,0,Yadira Pittman
4920,6920,Earth,False,55 Cancri e,20,False,0,0,0,335,957,Maliyah Morgan
4921,6921,Earth,False,PSO J318.5-22,42,False,0,168,0,113,461,Brynlee Gilbert
4922,6922,Europa,False,TRAPPIST-1e,29,False,0,2509,0,16,698,Micaela Nelson

In [15]:
X_test = df_test.copy()

We need to prepare both training and test datasets before working with a Machine Learning method. 

Consider the following tips:

1.   Remove columns that you think does not influence the class label (for example 'PassengerId');
2.   Use some encoding method with categorical data.

You are free to use any other pre-processing ideas. 

You could use for instance, one-hot encoding with categorical data, as was shown when we studied the heart disease dataset.

Number of categories on each categorical data:



1.   HomePlanet: 3
2.   Destination: 3

In [16]:
X_train1 = X_train[['HomePlanet','CryoSleep','Destination','VIP','Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']].copy()

In [17]:
X_train1['Total Spending']=X_train1['RoomService']+X_train1['FoodCourt']+X_train1['ShoppingMall']+X_train1['Spa']+X_train1['VRDeck']

In [18]:
X_train2=X_train1[['HomePlanet','CryoSleep','Destination','VIP','Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck','Total Spending']].copy()

In [19]:
X_train2

,HomePlanet,CryoSleep,Destination,VIP,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Total Spending
0,Earth,False,55 Cancri e,False,22,0,833,381,0,12,1226
1,Mars,True,TRAPPIST-1e,False,61,0,0,0,0,0,0
2,Mars,True,TRAPPIST-1e,False,5,0,0,0,0,0,0
3,Earth,False,55 Cancri e,False,14,653,0,4,0,0,657
4,Earth,False,PSO J318.5-22,False,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,Earth,False,TRAPPIST-1e,False,27,158,0,1271,0,71,1500
1996,Mars,False,55 Cancri e,False,51,40,716,1907,0,0,2663
1997,Mars,False,TRAPPIST-1e,False,32,689,0,610,0,0,1299
1998,Mars,True,TRAPPIST-1e,False,41,0,0,0,0,0,0
1999,Earth,False,TRAPPIST-1e,False,19,0,28,62,24,1686,1800

In [20]:
X_train2

,HomePlanet,CryoSleep,Destination,VIP,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Total Spending
0,Earth,False,55 Cancri e,False,22,0,833,381,0,12,1226
1,Mars,True,TRAPPIST-1e,False,61,0,0,0,0,0,0
2,Mars,True,TRAPPIST-1e,False,5,0,0,0,0,0,0
3,Earth,False,55 Cancri e,False,14,653,0,4,0,0,657
4,Earth,False,PSO J318.5-22,False,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,Earth,False,TRAPPIST-1e,False,27,158,0,1271,0,71,1500
1996,Mars,False,55 Cancri e,False,51,40,716,1907,0,0,2663
1997,Mars,False,TRAPPIST-1e,False,32,689,0,610,0,0,1299
1998,Mars,True,TRAPPIST-1e,False,41,0,0,0,0,0,0
1999,Earth,False,TRAPPIST-1e,False,19,0,28,62,24,1686,1800

In [21]:
X_test1 = X_test[['HomePlanet','CryoSleep','VIP','Destination','Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']].copy()
X_test1['Total Spending']=X_test1['RoomService']+X_test1['FoodCourt']+X_test1['ShoppingMall']+X_test1['Spa']+X_test1['VRDeck']
X_test2=X_test1[['HomePlanet','CryoSleep','Destination','VIP','Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck','Total Spending']].copy() #making new feature

In [22]:
X_train2

,HomePlanet,CryoSleep,Destination,VIP,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Total Spending
0,Earth,False,55 Cancri e,False,22,0,833,381,0,12,1226
1,Mars,True,TRAPPIST-1e,False,61,0,0,0,0,0,0
2,Mars,True,TRAPPIST-1e,False,5,0,0,0,0,0,0
3,Earth,False,55 Cancri e,False,14,653,0,4,0,0,657
4,Earth,False,PSO J318.5-22,False,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,Earth,False,TRAPPIST-1e,False,27,158,0,1271,0,71,1500
1996,Mars,False,55 Cancri e,False,51,40,716,1907,0,0,2663
1997,Mars,False,TRAPPIST-1e,False,32,689,0,610,0,0,1299
1998,Mars,True,TRAPPIST-1e,False,41,0,0,0,0,0,0
1999,Earth,False,TRAPPIST-1e,False,19,0,28,62,24,1686,1800

Preprocessing Pipeline

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [24]:
# Pipeline for numerical values
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),                              #Declaring StandardScaler encoding for the numerical dataset
    ("scaler", StandardScaler())
])

In [25]:
# Pipeline for categorical attributes

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("cat_encoder", OneHotEncoder(sparse=False))                                #Declaring one hot encoding for the catagorical dataset
])

In [26]:
# Combine the numerical and categorical pipelines

num_attribs = ["Age","RoomService","FoodCourt","ShoppingMall","Spa","VRDeck"]   #All numerical feature to be given to the pipeline
cat_attribs = ["CryoSleep", "VIP","HomePlanet", "Destination"]                  #All categorical feature to be given to the pipeline

preprocess_pipeline = ColumnTransformer([                                       #Fitting data into the pipeline for scaling and encoding
    ("num", num_pipeline, num_attribs),
    ("cat", cat_pipeline, cat_attribs)
])

In [27]:
X_train2 = preprocess_pipeline.fit_transform(
    X_train2[num_attribs + cat_attribs]
)
X_train2[0:10]

array([[-0.44822539, -0.34674719,  0.19009214,  0.42156563, -0.27686581,
        -0.2519652 ,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 2.21835841, -0.34674719, -0.2824472 , -0.32631229, -0.27686581,
        -0.26372046,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ],
       [-1.61058243, -0.34674719, -0.2824472 , -0.32631229, -0.27686581,
        -0.26372046,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ],
       [-0.99521693,  0.713992  , -0.2824472 , -0.31846055, -0.27686581,
        -0.26372046,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-1.81570426, -0.34674719, -0.2824472 , -0.32631229, -0.27686581,
        -0.26372046,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 0.1671401 , -0.04948032, -0.2824472 , -0.2634984 , -0.27686581,
         0.88339707,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-0.44822539, -0.34674719, -0.2824472 , -0.32631229, -0.27686581,
        -0.26372046,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-1.81570426, -0.34674719, -0.2824472 , -0.32631229, -0.27686581,
        -0.26372046,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.57738377,  0.1828102 , -0.2824472 ,  0.56682276, -0.27524791,
        -0.26372046,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ],
       [-0.58497327, -0.34674719, -0.11793771, -0.32631229,  1.23264066,
        -0.05114616,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ]])

In [28]:
X_test2 = preprocess_pipeline.fit_transform(X_test2[num_attribs + cat_attribs])
X_test2[0:10]

array([[ 1.72629481,  0.639009  , -0.28958347,  0.06842275,  0.06268011,
        -0.27282634,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.96586627,  0.1505511 , -0.28285374,  0.90242087, -0.2605216 ,
        -0.27282634,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.2745676 , -0.2215389 ,  1.16709607, -0.27255701,  2.97238335,
        -0.14405669,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.067178  , -0.33216025, -0.28958347, -0.27255701, -0.27384035,
        -0.27282634,  0.        ,  1.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.13630787, -0.33216025, -0.25715843, -0.27255701,  2.35705703,
         0.60023185,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [-0.55499081, -0.33216025, -0.28958347, -0.27255701, -0.27384035,
        -0.27282634,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.34369747, -0.33216025,  2.89785896, -0.27255701,  0.90886479,
        -0.27110941,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.96586627, -0.32210376,  0.01264236,  3.37784538,  0.11950678,
        -0.21187537,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.8967364 , -0.33216025, -0.28958347,  0.83452014, -0.27384035,
        -0.13890591,  1.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [ 0.41282733, -0.33216025, -0.28958347, -0.27255701, -0.27384035,
        -0.27282634,  0.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ]])

## GRAPE

<div>
<img src="https://drive.google.com/uc?export=view&id=1hw43Oi3lGTCkspQ0ged2bZB8q2EpcPhz" width="150"/>
</div> 

GRammatical Algorithms in Python for Evolution (GRAPE)

In [30]:
!pip install deap==1.3 

import grape
import algorithms

from os import path
from deap import creator, base, tools
import random
import csv

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: deap==1.3 in /usr/local/lib/python3.7/dist-packages (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from deap==1.3) (1.21.6)

You can import functions to be used with your grammar from [functions.py](https://github.com/UL-BDS/grape/blob/main/functions.py) on GRAPE repository and / or you can define your own functions.

In [31]:
from functions import add, sub, mul, pdiv, psqrt, plog, neg, and_, or_, not_, less_than_or_equal, greater_than_or_equal,nand_,nor_

In [32]:
def pexp(a):                                                                    #making functions we want to use in our grammar file
  return np.square(a)

def pneg(a):
  return np.multiply(a,-1)

def phalf(a):
  return np.multiply(a,0.5)

def psin(a):
  return np.sin(a)

def pcos(a):
  return np.cos(a)

def ptan(a):
  return np.tan(a)

def xor_(a, b):
    return np.logical_xor(a,b)
    
def mean_(a):
    return np.mean(a)

In [34]:
GRAMMAR_FILE = 'SpaceShip_10_feature_final.bnf'                                 #importing grammar file from drive
f = open("grammars/" + GRAMMAR_FILE, "r")
print(f.read())                                                                 #reading and printing the grammar
f.close()

<log_op> ::= <conditional_branches> | and_(<log_op>,<log_op>) | or_(<log_op>,<log_op>) | not_(<log_op>) | <boolean_feature> | nand_(<log_op>,<log_op>) | nor_(<log_op>,<log_op>) | xor_(<log_op>,<log_op>) | not_(<boolean_feature>)
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<o> ::= +|-|*
<conditional_branches> ::= less_than_or_equal(<num_op>,<num_op>) | greater_than_or_equal(<num_op>, <num_op>)
<num_op>   ::= add(<num_op>,<num_op>) | sub(<num_op>,<num_op>) | mul(<num_op>,<num_op>) | pdiv(<num_op>,<num_op>) | <nonboolean_feature> | <nonboolean_feature> <o> <nonboolean_feature> | <nonboolean_feature> | <nonboolean_feature> <o> <nonboolean_feature>
<boolean_feature> ::= x[6]|x[7]|x[8]|x[9]|x[10]|x[11]|x[12]|x[13]|x[14]|x[15]
<nonboolean_feature> ::= x[0]|x[1]|x[2]|x[3]|x[4]|x[5]|<c><c>.<c><c>|mean_(<nonboolean_feature>)

Run the following cell to put your grammar on the class Grammar.

In [35]:
BNF_GRAMMAR = grape.Grammar(path.join("grammars", GRAMMAR_FILE))                #utilising the grammar in the grape library

In [36]:
def fitness_eval(individual, points):
    """
    Fitness Function
    """

    x = points[0]
    Y = points[1]
    
    if individual.invalid == True:
        return np.NaN,

    # Evaluate the expression
    try:
        pred = eval(individual.phenotype)
    except (FloatingPointError, ZeroDivisionError, OverflowError,
            MemoryError):
        return np.NaN,
    assert np.isrealobj(pred)

    compare = np.equal(Y,pred)
    fitness = 1 - np.mean(compare)
   
    return fitness,

In [37]:
X_train2 = np.transpose(X_train2)                                               #using transpose to fit the feature in the evaluation function and printing to see the shape
X_test2 = np.transpose(X_test2)                                                 

print('Training (X,Y):\t', X_train2.shape, y_train.shape)
print('Test (X):\t', X_test2.shape)

Training (X,Y):	 (16, 2000) (2000,)
Test (X):	 (16, 4923)

Set the Grammatical Evolution parameters.

In [38]:

POPULATION_SIZE = 10000                                                         #declaring parameters for the GE to take place
MAX_GENERATIONS = 500
P_CROSSOVER = 0.85
P_MUTATION = 0.05
ELITE_SIZE = 1
HALL_OFFAME_SIZE = 1

TOURNAMENT_SIZE = 10                                                            #using 10 for tournament size
RANDOM_SEED = 42                                                                #fixing seed to 42 as constant
random.seed(RANDOM_SEED) 

CODON_CONSUMPTION = 'eager'
GENOME_REPRESENTATION = 'list'
MAX_GENOME_LENGTH = None

MAX_INIT_TREE_DEPTH = 10
MIN_INIT_TREE_DEPTH = 5
MAX_TREE_DEPTH = 250
MAX_WRAPS = 1                                                                   #using max wrap 1 to allow wrapping 
CODON_SIZE = 255

REPORT_ITEMS = ['gen', 'invalid', 'avg', 'std', 'min', 'max', 
                'best_ind_length', 'avg_length', 
                'best_ind_nodes', 'avg_nodes', 
                'best_ind_depth', 'avg_depth', 
                'avg_used_codons', 'best_ind_used_codons',
                'structural_diversity', 'fitness_diversity',
                'selection_time', 'generation_time']

Create a toolbox.

In [39]:
toolbox = base.Toolbox()

# define a single objective, minimising fitness strategy:
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))                     #setting weights to -1 to minimise the fitness score as objective
creator.create('Individual', grape.Individual, fitness=creator.FitnessMin)

toolbox.register("populationCreator", grape.sensible_initialisation, creator.Individual)  #using sensible initialisation

toolbox.register("evaluate", fitness_eval)

# Tournament selection:
toolbox.register("select", tools.selTournament, tournsize=TOURNAMENT_SIZE)      #declaring selTournament for tournament selection

# Single-point crossover:
toolbox.register("mate", grape.crossover_onepoint)

# Flip-int mutation:
toolbox.register("mutate", grape.mutation_int_flip_per_codon)

In [40]:
# create initial population (generation 0):
population = toolbox.populationCreator(pop_size=POPULATION_SIZE, 
                                           bnf_grammar=BNF_GRAMMAR, 
                                           min_init_depth=MIN_INIT_TREE_DEPTH,
                                           max_init_depth=MAX_INIT_TREE_DEPTH,
                                           codon_size=CODON_SIZE,
                                           codon_consumption=CODON_CONSUMPTION,
                                           genome_representation=GENOME_REPRESENTATION
                                            )

# define the hall-of-fame object:
hof = tools.HallOfFame(HALL_OFFAME_SIZE)

# prepare the statistics object:
stats = tools.Statistics(key=lambda ind: ind.fitness.values)
stats.register("avg", np.nanmean)
stats.register("std", np.nanstd)
stats.register("min", np.nanmin)
stats.register("max", np.nanmax)

Run Grammatical Evolution.

In [41]:
population, logbook = algorithms.ge_eaSimpleWithElitism(population, toolbox, cxpb=P_CROSSOVER, mutpb=P_MUTATION,
                                              ngen=MAX_GENERATIONS, elite_size=ELITE_SIZE,
                                              bnf_grammar=BNF_GRAMMAR, 
                                              codon_size=CODON_SIZE, 
                                              max_tree_depth=MAX_TREE_DEPTH,
                                              max_genome_length=MAX_GENOME_LENGTH,
                                              points_train=[X_train2, y_train], 
                                              codon_consumption=CODON_CONSUMPTION,
                                              report_items=REPORT_ITEMS,
                                              genome_representation=GENOME_REPRESENTATION,                                              
                                              stats=stats, halloffame=hof, verbose=False)

gen = 0 , Best fitness = (0.27249999999999996,)
gen = 1 , Best fitness = (0.253,) , Number of invalids = 4404
gen = 2 , Best fitness = (0.253,) , Number of invalids = 4937
gen = 3 , Best fitness = (0.253,) , Number of invalids = 5035
gen = 4 , Best fitness = (0.253,) , Number of invalids = 5125
gen = 5 , Best fitness = (0.253,) , Number of invalids = 5135
gen = 6 , Best fitness = (0.253,) , Number of invalids = 5180
gen = 7 , Best fitness = (0.23950000000000005,) , Number of invalids = 5101
gen = 8 , Best fitness = (0.23950000000000005,) , Number of invalids = 5054
gen = 9 , Best fitness = (0.23950000000000005,) , Number of invalids = 4931
gen = 10 , Best fitness = (0.23950000000000005,) , Number of invalids = 4830
gen = 11 , Best fitness = (0.23950000000000005,) , Number of invalids = 4755
gen = 12 , Best fitness = (0.23950000000000005,) , Number of invalids = 4662
gen = 13 , Best fitness = (0.23950000000000005,) , Number of invalids = 4647
gen = 14 , Best fitness = (0.23950000000000005,) , Number of invalids = 4638
gen = 15 , Best fitness = (0.23950000000000005,) , Number of invalids = 4577
gen = 16 , Best fitness = (0.23950000000000005,) , Number of invalids = 4507
gen = 17 , Best fitness = (0.23950000000000005,) , Number of invalids = 4445
gen = 18 , Best fitness = (0.23950000000000005,) , Number of invalids = 4450
gen = 19 , Best fitness = (0.23950000000000005,) , Number of invalids = 4382
gen = 20 , Best fitness = (0.23950000000000005,) , Number of invalids = 4305
gen = 21 , Best fitness = (0.23950000000000005,) , Number of invalids = 4218
gen = 22 , Best fitness = (0.23950000000000005,) , Number of invalids = 4154
gen = 23 , Best fitness = (0.23950000000000005,) , Number of invalids = 4158
gen = 24 , Best fitness = (0.23950000000000005,) , Number of invalids = 4024
gen = 25 , Best fitness = (0.23950000000000005,) , Number of invalids = 4002
gen = 26 , Best fitness = (0.23950000000000005,) , Number of invalids = 4061
gen = 27 , Best fitness = (0.23950000000000005,) , Number of invalids = 4025
gen = 28 , Best fitness = (0.23950000000000005,) , Number of invalids = 3985
gen = 29 , Best fitness = (0.23950000000000005,) , Number of invalids = 3907
gen = 30 , Best fitness = (0.23950000000000005,) , Number of invalids = 3861
gen = 31 , Best fitness = (0.23950000000000005,) , Number of invalids = 3759
gen = 32 , Best fitness = (0.23950000000000005,) , Number of invalids = 3778
gen = 33 , Best fitness = (0.23950000000000005,) , Number of invalids = 3787
gen = 34 , Best fitness = (0.23950000000000005,) , Number of invalids = 3745
gen = 35 , Best fitness = (0.23950000000000005,) , Number of invalids = 3781
gen = 36 , Best fitness = (0.23950000000000005,) , Number of invalids = 3666
gen = 37 , Best fitness = (0.23950000000000005,) , Number of invalids = 3748
gen = 38 , Best fitness = (0.23950000000000005,) , Number of invalids = 3708
gen = 39 , Best fitness = (0.23950000000000005,) , Number of invalids = 3685
gen = 40 , Best fitness = (0.23950000000000005,) , Number of invalids = 3696
gen = 41 , Best fitness = (0.23950000000000005,) , Number of invalids = 3655
gen = 42 , Best fitness = (0.23950000000000005,) , Number of invalids = 3596
gen = 43 , Best fitness = (0.23950000000000005,) , Number of invalids = 3529
gen = 44 , Best fitness = (0.23950000000000005,) , Number of invalids = 3490
gen = 45 , Best fitness = (0.23950000000000005,) , Number of invalids = 3416
gen = 46 , Best fitness = (0.23950000000000005,) , Number of invalids = 3399
gen = 47 , Best fitness = (0.23950000000000005,) , Number of invalids = 3372
gen = 48 , Best fitness = (0.23950000000000005,) , Number of invalids = 3327
gen = 49 , Best fitness = (0.23950000000000005,) , Number of invalids = 3420
gen = 50 , Best fitness = (0.23950000000000005,) , Number of invalids = 3387
gen = 51 , Best fitness = (0.23950000000000005,) , Number of invalids = 3331
gen = 52 , Best fitness = (0.23950000000000005,) , Number of invalids = 3303
gen = 53 , Best fitness = (0.23950000000000005,) , Number of invalids = 3302
gen = 54 , Best fitness = (0.23950000000000005,) , Number of invalids = 3394
gen = 55 , Best fitness = (0.23950000000000005,) , Number of invalids = 3335
gen = 56 , Best fitness = (0.23950000000000005,) , Number of invalids = 3312
gen = 57 , Best fitness = (0.23950000000000005,) , Number of invalids = 3339
gen = 58 , Best fitness = (0.23950000000000005,) , Number of invalids = 3482
gen = 59 , Best fitness = (0.23950000000000005,) , Number of invalids = 3470
gen = 60 , Best fitness = (0.23950000000000005,) , Number of invalids = 3449
gen = 61 , Best fitness = (0.23950000000000005,) , Number of invalids = 3456
gen = 62 , Best fitness = (0.23950000000000005,) , Number of invalids = 3453
gen = 63 , Best fitness = (0.23950000000000005,) , Number of invalids = 3497
gen = 64 , Best fitness = (0.23950000000000005,) , Number of invalids = 3488
gen = 65 , Best fitness = (0.23950000000000005,) , Number of invalids = 3487
gen = 66 , Best fitness = (0.23950000000000005,) , Number of invalids = 3509
gen = 67 , Best fitness = (0.23950000000000005,) , Number of invalids = 3479
gen = 68 , Best fitness = (0.23950000000000005,) , Number of invalids = 3448
gen = 69 , Best fitness = (0.23950000000000005,) , Number of invalids = 3579
gen = 70 , Best fitness = (0.23950000000000005,) , Number of invalids = 3523
gen = 71 , Best fitness = (0.23950000000000005,) , Number of invalids = 3520
gen = 72 , Best fitness = (0.23950000000000005,) , Number of invalids = 3513
gen = 73 , Best fitness = (0.23950000000000005,) , Number of invalids = 3654
gen = 74 , Best fitness = (0.23950000000000005,) , Number of invalids = 3646
gen = 75 , Best fitness = (0.23950000000000005,) , Number of invalids = 3710
gen = 76 , Best fitness = (0.23950000000000005,) , Number of invalids = 3681
gen = 77 , Best fitness = (0.23950000000000005,) , Number of invalids = 3627
gen = 78 , Best fitness = (0.23950000000000005,) , Number of invalids = 3645
gen = 79 , Best fitness = (0.23950000000000005,) , Number of invalids = 3620
gen = 80 , Best fitness = (0.23950000000000005,) , Number of invalids = 3616
gen = 81 , Best fitness = (0.23950000000000005,) , Number of invalids = 3657
gen = 82 , Best fitness = (0.23950000000000005,) , Number of invalids = 3688
gen = 83 , Best fitness = (0.23950000000000005,) , Number of invalids = 3722
gen = 84 , Best fitness = (0.23950000000000005,) , Number of invalids = 3758
gen = 85 , Best fitness = (0.23950000000000005,) , Number of invalids = 3803
gen = 86 , Best fitness = (0.23950000000000005,) , Number of invalids = 3713
gen = 87 , Best fitness = (0.23950000000000005,) , Number of invalids = 3680
gen = 88 , Best fitness = (0.23950000000000005,) , Number of invalids = 3794
gen = 89 , Best fitness = (0.23950000000000005,) , Number of invalids = 3834
gen = 90 , Best fitness = (0.23950000000000005,) , Number of invalids = 3837
gen = 91 , Best fitness = (0.23950000000000005,) , Number of invalids = 3820
gen = 92 , Best fitness = (0.23950000000000005,) , Number of invalids = 3801
gen = 93 , Best fitness = (0.23950000000000005,) , Number of invalids = 3888
gen = 94 , Best fitness = (0.23950000000000005,) , Number of invalids = 3921
gen = 95 , Best fitness = (0.23950000000000005,) , Number of invalids = 3943
gen = 96 , Best fitness = (0.23950000000000005,) , Number of invalids = 3900
gen = 97 , Best fitness = (0.23950000000000005,) , Number of invalids = 4050
gen = 98 , Best fitness = (0.23950000000000005,) , Number of invalids = 4048
gen = 99 , Best fitness = (0.23950000000000005,) , Number of invalids = 4141
gen = 100 , Best fitness = (0.23950000000000005,) , Number of invalids = 4025
gen = 101 , Best fitness = (0.23950000000000005,) , Number of invalids = 3996
gen = 102 , Best fitness = (0.23950000000000005,) , Number of invalids = 4008
gen = 103 , Best fitness = (0.23950000000000005,) , Number of invalids = 4010
gen = 104 , Best fitness = (0.23950000000000005,) , Number of invalids = 4068
gen = 105 , Best fitness = (0.23950000000000005,) , Number of invalids = 4142
gen = 106 , Best fitness = (0.23950000000000005,) , Number of invalids = 4243
gen = 107 , Best fitness = (0.23950000000000005,) , Number of invalids = 4233
gen = 108 , Best fitness = (0.23950000000000005,) , Number of invalids = 4200
gen = 109 , Best fitness = (0.23950000000000005,) , Number of invalids = 4262
gen = 110 , Best fitness = (0.23950000000000005,) , Number of invalids = 4256
gen = 111 , Best fitness = (0.23950000000000005,) , Number of invalids = 4212
gen = 112 , Best fitness = (0.23950000000000005,) , Number of invalids = 4145
gen = 113 , Best fitness = (0.23950000000000005,) , Number of invalids = 4240
gen = 114 , Best fitness = (0.23950000000000005,) , Number of invalids = 4274
gen = 115 , Best fitness = (0.23950000000000005,) , Number of invalids = 4265
gen = 116 , Best fitness = (0.23950000000000005,) , Number of invalids = 4259
gen = 117 , Best fitness = (0.23950000000000005,) , Number of invalids = 4326
gen = 118 , Best fitness = (0.23950000000000005,) , Number of invalids = 4281
gen = 119 , Best fitness = (0.23950000000000005,) , Number of invalids = 4282
gen = 120 , Best fitness = (0.23950000000000005,) , Number of invalids = 4303
gen = 121 , Best fitness = (0.23950000000000005,) , Number of invalids = 4337
gen = 122 , Best fitness = (0.23950000000000005,) , Number of invalids = 4425
gen = 123 , Best fitness = (0.23950000000000005,) , Number of invalids = 4432
gen = 124 , Best fitness = (0.23950000000000005,) , Number of invalids = 4427
gen = 125 , Best fitness = (0.23950000000000005,) , Number of invalids = 4511
gen = 126 , Best fitness = (0.23950000000000005,) , Number of invalids = 4457
gen = 127 , Best fitness = (0.23950000000000005,) , Number of invalids = 4464
gen = 128 , Best fitness = (0.23950000000000005,) , Number of invalids = 4555
gen = 129 , Best fitness = (0.23950000000000005,) , Number of invalids = 4588
gen = 130 , Best fitness = (0.23950000000000005,) , Number of invalids = 4624
gen = 131 , Best fitness = (0.23950000000000005,) , Number of invalids = 4666
gen = 132 , Best fitness = (0.23950000000000005,) , Number of invalids = 4628
gen = 133 , Best fitness = (0.23950000000000005,) , Number of invalids = 4704
gen = 134 , Best fitness = (0.23950000000000005,) , Number of invalids = 4802
gen = 135 , Best fitness = (0.23950000000000005,) , Number of invalids = 4888
gen = 136 , Best fitness = (0.23950000000000005,) , Number of invalids = 4801
gen = 137 , Best fitness = (0.23950000000000005,) , Number of invalids = 4749
gen = 138 , Best fitness = (0.23950000000000005,) , Number of invalids = 4636
gen = 139 , Best fitness = (0.23950000000000005,) , Number of invalids = 4696
gen = 140 , Best fitness = (0.23950000000000005,) , Number of invalids = 4695
gen = 141 , Best fitness = (0.23950000000000005,) , Number of invalids = 4714
gen = 142 , Best fitness = (0.23950000000000005,) , Number of invalids = 4736
gen = 143 , Best fitness = (0.23950000000000005,) , Number of invalids = 4834
gen = 144 , Best fitness = (0.23950000000000005,) , Number of invalids = 4795
gen = 145 , Best fitness = (0.23950000000000005,) , Number of invalids = 4780
gen = 146 , Best fitness = (0.23950000000000005,) , Number of invalids = 4777
gen = 147 , Best fitness = (0.23950000000000005,) , Number of invalids = 4757
gen = 148 , Best fitness = (0.23950000000000005,) , Number of invalids = 4854
gen = 149 , Best fitness = (0.23950000000000005,) , Number of invalids = 4797
gen = 150 , Best fitness = (0.23950000000000005,) , Number of invalids = 4804
gen = 151 , Best fitness = (0.23950000000000005,) , Number of invalids = 4877
gen = 152 , Best fitness = (0.23950000000000005,) , Number of invalids = 4865
gen = 153 , Best fitness = (0.23950000000000005,) , Number of invalids = 4888
gen = 154 , Best fitness = (0.23950000000000005,) , Number of invalids = 4891
gen = 155 , Best fitness = (0.23950000000000005,) , Number of invalids = 4952
gen = 156 , Best fitness = (0.23950000000000005,) , Number of invalids = 4947
gen = 157 , Best fitness = (0.23950000000000005,) , Number of invalids = 4975
gen = 158 , Best fitness = (0.23950000000000005,) , Number of invalids = 4949
gen = 159 , Best fitness = (0.23950000000000005,) , Number of invalids = 4964
gen = 160 , Best fitness = (0.23950000000000005,) , Number of invalids = 4898
gen = 161 , Best fitness = (0.23950000000000005,) , Number of invalids = 4933
gen = 162 , Best fitness = (0.23950000000000005,) , Number of invalids = 5059
gen = 163 , Best fitness = (0.23950000000000005,) , Number of invalids = 5127
gen = 164 , Best fitness = (0.23950000000000005,) , Number of invalids = 5118
gen = 165 , Best fitness = (0.23950000000000005,) , Number of invalids = 5166
gen = 166 , Best fitness = (0.23950000000000005,) , Number of invalids = 5154
gen = 167 , Best fitness = (0.23950000000000005,) , Number of invalids = 5143
gen = 168 , Best fitness = (0.23950000000000005,) , Number of invalids = 5186
gen = 169 , Best fitness = (0.23950000000000005,) , Number of invalids = 5251
gen = 170 , Best fitness = (0.23950000000000005,) , Number of invalids = 5320
gen = 171 , Best fitness = (0.23950000000000005,) , Number of invalids = 5351
gen = 172 , Best fitness = (0.23950000000000005,) , Number of invalids = 5370
gen = 173 , Best fitness = (0.23950000000000005,) , Number of invalids = 5391
gen = 174 , Best fitness = (0.23950000000000005,) , Number of invalids = 5332
gen = 175 , Best fitness = (0.23950000000000005,) , Number of invalids = 5351
gen = 176 , Best fitness = (0.23950000000000005,) , Number of invalids = 5460
gen = 177 , Best fitness = (0.23950000000000005,) , Number of invalids = 5546
gen = 178 , Best fitness = (0.23950000000000005,) , Number of invalids = 5572
gen = 179 , Best fitness = (0.23950000000000005,) , Number of invalids = 5618
gen = 180 , Best fitness = (0.23950000000000005,) , Number of invalids = 5672
gen = 181 , Best fitness = (0.23950000000000005,) , Number of invalids = 5697
gen = 182 , Best fitness = (0.23950000000000005,) , Number of invalids = 5728
gen = 183 , Best fitness = (0.23950000000000005,) , Number of invalids = 5725
gen = 184 , Best fitness = (0.23950000000000005,) , Number of invalids = 5632
gen = 185 , Best fitness = (0.23950000000000005,) , Number of invalids = 5651
gen = 186 , Best fitness = (0.23950000000000005,) , Number of invalids = 5628
gen = 187 , Best fitness = (0.23950000000000005,) , Number of invalids = 5627
gen = 188 , Best fitness = (0.23950000000000005,) , Number of invalids = 5609
gen = 189 , Best fitness = (0.23950000000000005,) , Number of invalids = 5603
gen = 190 , Best fitness = (0.23950000000000005,) , Number of invalids = 5651
gen = 191 , Best fitness = (0.23950000000000005,) , Number of invalids = 5617
gen = 192 , Best fitness = (0.23950000000000005,) , Number of invalids = 5507
gen = 193 , Best fitness = (0.23950000000000005,) , Number of invalids = 5483
gen = 194 , Best fitness = (0.23950000000000005,) , Number of invalids = 5563
gen = 195 , Best fitness = (0.23950000000000005,) , Number of invalids = 5653
gen = 196 , Best fitness = (0.23950000000000005,) , Number of invalids = 5670
gen = 197 , Best fitness = (0.23950000000000005,) , Number of invalids = 5737
gen = 198 , Best fitness = (0.23950000000000005,) , Number of invalids = 5763
gen = 199 , Best fitness = (0.23950000000000005,) , Number of invalids = 5800
gen = 200 , Best fitness = (0.23950000000000005,) , Number of invalids = 5815
gen = 201 , Best fitness = (0.23950000000000005,) , Number of invalids = 5797
gen = 202 , Best fitness = (0.23950000000000005,) , Number of invalids = 5792
gen = 203 , Best fitness = (0.23950000000000005,) , Number of invalids = 5763
gen = 204 , Best fitness = (0.23950000000000005,) , Number of invalids = 5877
gen = 205 , Best fitness = (0.23950000000000005,) , Number of invalids = 5945
gen = 206 , Best fitness = (0.23950000000000005,) , Number of invalids = 5945
gen = 207 , Best fitness = (0.23950000000000005,) , Number of invalids = 5884
gen = 208 , Best fitness = (0.23950000000000005,) , Number of invalids = 5938
gen = 209 , Best fitness = (0.23950000000000005,) , Number of invalids = 5920
gen = 210 , Best fitness = (0.23950000000000005,) , Number of invalids = 5926
gen = 211 , Best fitness = (0.23950000000000005,) , Number of invalids = 5892
gen = 212 , Best fitness = (0.23950000000000005,) , Number of invalids = 5935
gen = 213 , Best fitness = (0.23950000000000005,) , Number of invalids = 5977
gen = 214 , Best fitness = (0.23950000000000005,) , Number of invalids = 6047
gen = 215 , Best fitness = (0.23950000000000005,) , Number of invalids = 6147
gen = 216 , Best fitness = (0.23950000000000005,) , Number of invalids = 6215
gen = 217 , Best fitness = (0.23950000000000005,) , Number of invalids = 6291
gen = 218 , Best fitness = (0.23950000000000005,) , Number of invalids = 6208
gen = 219 , Best fitness = (0.23950000000000005,) , Number of invalids = 6257
gen = 220 , Best fitness = (0.23950000000000005,) , Number of invalids = 6292
gen = 221 , Best fitness = (0.23950000000000005,) , Number of invalids = 6243
gen = 222 , Best fitness = (0.23950000000000005,) , Number of invalids = 6326
gen = 223 , Best fitness = (0.23950000000000005,) , Number of invalids = 6278
gen = 224 , Best fitness = (0.23950000000000005,) , Number of invalids = 6274
gen = 225 , Best fitness = (0.23950000000000005,) , Number of invalids = 6287
gen = 226 , Best fitness = (0.23950000000000005,) , Number of invalids = 6270
gen = 227 , Best fitness = (0.23950000000000005,) , Number of invalids = 6262
gen = 228 , Best fitness = (0.23950000000000005,) , Number of invalids = 6187
gen = 229 , Best fitness = (0.23950000000000005,) , Number of invalids = 6207
gen = 230 , Best fitness = (0.23950000000000005,) , Number of invalids = 6196
gen = 231 , Best fitness = (0.23950000000000005,) , Number of invalids = 6351
gen = 232 , Best fitness = (0.23950000000000005,) , Number of invalids = 6321
gen = 233 , Best fitness = (0.23950000000000005,) , Number of invalids = 6311
gen = 234 , Best fitness = (0.23950000000000005,) , Number of invalids = 6295
gen = 235 , Best fitness = (0.23950000000000005,) , Number of invalids = 6295
gen = 236 , Best fitness = (0.23950000000000005,) , Number of invalids = 6326
gen = 237 , Best fitness = (0.23950000000000005,) , Number of invalids = 6295
gen = 238 , Best fitness = (0.23950000000000005,) , Number of invalids = 6260
gen = 239 , Best fitness = (0.23950000000000005,) , Number of invalids = 6315
gen = 240 , Best fitness = (0.23950000000000005,) , Number of invalids = 6276
gen = 241 , Best fitness = (0.23950000000000005,) , Number of invalids = 6279
gen = 242 , Best fitness = (0.23950000000000005,) , Number of invalids = 6302
gen = 243 , Best fitness = (0.23950000000000005,) , Number of invalids = 6333
gen = 244 , Best fitness = (0.23950000000000005,) , Number of invalids = 6448
gen = 245 , Best fitness = (0.23950000000000005,) , Number of invalids = 6542
gen = 246 , Best fitness = (0.23950000000000005,) , Number of invalids = 6653
gen = 247 , Best fitness = (0.23950000000000005,) , Number of invalids = 6634
gen = 248 , Best fitness = (0.23950000000000005,) , Number of invalids = 6664
gen = 249 , Best fitness = (0.23950000000000005,) , Number of invalids = 6628
gen = 250 , Best fitness = (0.23950000000000005,) , Number of invalids = 6710
gen = 251 , Best fitness = (0.23950000000000005,) , Number of invalids = 6704
gen = 252 , Best fitness = (0.23950000000000005,) , Number of invalids = 6647
gen = 253 , Best fitness = (0.23950000000000005,) , Number of invalids = 6690
gen = 254 , Best fitness = (0.23950000000000005,) , Number of invalids = 6680
gen = 255 , Best fitness = (0.23950000000000005,) , Number of invalids = 6765
gen = 256 , Best fitness = (0.23950000000000005,) , Number of invalids = 6748
gen = 257 , Best fitness = (0.23950000000000005,) , Number of invalids = 6744
gen = 258 , Best fitness = (0.23950000000000005,) , Number of invalids = 6826

Show the best individual as an expression.

In [42]:
# Best individual
import textwrap
best = hof.items[0].phenotype
print("Best individual: \n","\n".join(textwrap.wrap(best,80)))
print("\nTraining Fitness: ", hof.items[0].fitness.values[0])
print("Depth: ", hof.items[0].depth)
print("Length of the genome: ", len(hof.items[0].genome))
print(f'Used portion of the genome: {hof.items[0].used_codons/len(hof.items[0].genome):.2f}')

Best individual:
 greater_than_or_equal(add(x[5] * x[1],x[2]), add(mul(pdiv(mean_(x[3]) *
x[4],sub(mul(mul(add(mul(x[1],sub(x[1],31.11 - 42.68)),x[3]),sub(x[2] +
x[4],mul(x[4] - x[3],mean_(x[2])))),x[4]),x[5] + x[4])),sub(sub(x[3] -
x[4],mean_(x[3])),x[0] - x[2])),x[4]))

Training Fitness:  0.23950000000000005
Depth:  15
Length of the genome:  223
Used portion of the genome: 0.34

Define a function to predict values.

In [43]:
def predict(individual, X):
    x = X
    
    if individual.invalid == True:
        return np.NaN,

    # Evaluate the expression
    try:
        pred = eval(individual.phenotype)
    except (FloatingPointError, ZeroDivisionError, OverflowError,
            MemoryError):
        return np.NaN,
    assert np.isrealobj(pred)
    
    _, c = x.shape
    
    try:
        Y_class = [True if pred[i] > 0 else False for i in range(c)]
    except (IndexError, TypeError):
        return np.NaN,
   
    return Y_class

Predict the classes of the test set.

In [44]:
y_pred = predict(hof.items[0], X_test2)
print("Predicted classes of the test set: ", y_pred)                            #check the predictions and printing

Predicted classes of the test set:  [False, False, False, True, False, True, True, False, True, True, True, True, True, False, True, False, False, True, True, True, True, False, False, True, True, True, True, True, True, True, True, True, False, False, False, True, True, True, True, True, True, True, True, False, True, True, False, True, True, False, True, True, True, True, False, False, True, True, True, False, True, True, False, True, True, True, True, False, False, True, True, True, False, True, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False, False, True, True, True, True, True, True, False, True, True, False, True, True, False, False, True, False, False, False, True, True, True, False, True, False, True, False, False, True, False, False, False, True, False, True, True, True, True, True, True, True, False, True, True, True, True, True, False, True, False, False, False, True, True, True, True, True, True, False, True, False, True, True, True, False, True, True, True, False, False, False, True, True, False, False, True, True, True, True, True, True, True, True, True, True, False, False, False, True, True, True, True, False, False, False, True, True, False, True, True, True, True, False, True, False, False, True, False, True, True, True, False, False, True, True, True, True, True, True, False, True, False, True, False, True, False, False, True, False, True, True, True, True, False, False, False, False, True, True, False, True, True, True, True, True, True, True, True, True, True, False, True, False, False, True, True, True, True, True, False, True, False, True, True, True, True, True, False, True, True, False, True, False, True, True, False, True, True, True, False, True, False, True, False, True, True, True, True, False, False, True, True, True, True, True, True, False, True, False, True, False, False, True, True, True, False, False, True, True, True, True, False, False, False, True, False, True, True, True, False, True, True, True, True, True, False, True, False, False, True, False, False, True, False, True, False, False, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, False, False, False, True, True, False, True, False, False, True, True, True, True, True, True, False, True, True, False, True, False, True, False, True, False, False, False, True, True, True, True, True, False, False, True, False, False, False, False, True, True, True, True, False, False, False, False, True, False, False, False, False, True, True, True, False, False, True, True, True, True, False, True, True, True, False, True, True, False, True, False, False, False, False, True, True, True, True, False, False, False, True, True, False, True, True, False, True, True, True, False, True, False, False, False, True, False, True, True, True, False, True, True, False, True, True, False, False, True, True, False, True, True, True, True, False, False, False, True, True, False, False, False, False, True, False, False, True, True, True, True, True, True, False, True, False, True, False, True, False, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, False, False, True, True, False, True, True, True, False, True, True, True, False, True, True, False, True, False, True, True, True, True, False, False, True, False, False, False, True, False, False, True, True, True, False, False, True, False, False, True, False, True, True, True, True, True, True, False, True, True, True, False, True, True, True, False, False, True, True, False, True, False, True, False, False, True, True, False, True, True, False, True, True, True, False, False, False, True, False, True, False, True, True, True, True, True, False, False, True, True, False, True, False, True, True, False, True, True, True, True, False, False, False, False, False, False, True, True, True, False, False, True, False, True, False, True, True, True, False, True, True, True, True, True, False, True, True, True, False, False, True, False, True, True, True, True, False, False, True, True, True, True, False, False, True, True, False, False, True, True, True, True, True, False, True, True, False, True, True, False, False, True, False, True, True, True, True, False, True, True, False, True, True, True, False, True, False, False, False, False, True, True, False, False, True, False, False, True, False, False, False, True, True, True, True, True, True, False, False, True, False, True, False, False, True, True, False, False, False, False, True, True, False, True, False, True, True, True, True, True, False, False, True, True, True, False, True, True, True, False, False, False, False, False, True, False, True, True, True, False, False, False, True, False, True, True, False, True, True, True, True, True, False, True, True, False, True, True, True, True, True, True, False, False, True, False, True, False, False, True, False, True, True, True, True, True, True, True, True, True, False, True, True, True, True, False, True, True, True, True, False, False, True, False, False, True, False, True, False, False, True, True, True, False, True, True, True, False, False, True, True, False, True, False, True, True, True, True, False, True, True, True, True, True, True, True, True, True, False, True, True, True, True, False, True, True, True, True, False, False, False, True, True, True, True, True, False, True, False, True, True, False, False, False, True, False, False, True, True, True, True, True, False, True, True, True, True, False, True, True, True, True, True, False, True, True, True, True, True, False, True, True, True, True, False, False, True, True, True, True, True, False, True, True, True, False, True, False, True, False, True, True, False, True, True, True, True, False, False, False, True, True, True, False, True, False, True, True, True, True, False, True, True, True, True, False, True, False, True, True, False, False, True, True, True, False, False, True, True, True, True, True, True, True, False, True, True, True, False, False, False, True, True, True, True, True, True, True, True, True, False, True, False, True, False, True, True, False, True, True, True, False, True, True, False, True, True, True, True, True, False, False, True, True, True, True, True, False, True, True, False, True, True, True, True, False, True, True, True, False, False, True, True, True, False, True, False, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, False, True, True, True, True, True, False, True, False, False, True, True, True, True, False, True, False, False, True, False, False, False, False, True, True, False, False, True, False, False, False, True, False, False, False, True, True, False, True, True, True, True, True, True, False, False, False, True, False, False, False, True, True, True, True, False, True, False, True, False, True, False, False, True, True, False, True, True, False, False, False, False, True, False, True, True, True, False, True, True, False, True, True, True, False, True, False, True, False, True, True, True, False, False, True, True, True, True, True, False, False, True, True, True, False, True, False, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, False, False, False, False, False, True, True, True, False, False, False, True, False, True, True, True, False, False, True, False, False, True, False, True, True, True, True, True, True, False, False, True, False, True, True, False, True, True, False, False, True, True, False, True, True, False, True, True, False, True, False, True, True, True, True, False, False, True, True, False, False, True, False, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, False, False, True, True, False, True, True, True, True, True, True, False, True, True, True, True, True, True, False, True, True, True, False, True, False, True, True, False, False, True, False, True, True, True, False, False, False, True, False, True, True, True, True, True, True, True, False, False, True, True, True, True, True, False, True, False, True, True, True, False, True, True, True, False, False, False, False, False, False, True, True, True, True, True, False, True, True, False, True, True, False, True, False, False, True, True, True, True, True, False, False, False, True, True, False, False, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, False, True, True, False, True, True, True, False, True, False, False, True, True, True, True, True, False, True, True, True, True, True, False, True, False, True, False, True, False, True, True, False, True, False, True, True, False, True, False, True, True, False, True, False, False, True, True, True, False, True, False, True, True, True, True, True, False, True, True, True, True, False, True, True, False, False, True, True, False, True, False, False, True, True, False, True, True, False, True, True, True, False, True, True, False, True, True, True, False, False, True, True, False, False, False, False, True, True, False, False, True, False, False, False, True, True, False, True, False, True, False, True, True, True, False, True, True, True, False, False, False, True, True, False, False, False, True, True, False, False, True, True, False, True, True, False, True, False, False, True, True, True, False, False, True, False, True, False, False, True, True, True, False, True, False, True, False, True, True, True, True, True, False, False, True, True, True, True, False, False, False, False, True, True, False, False, True, True, False, True, True, True, True, False, True, True, True, True, True, False, False, True, False, True, True, True, True, True, False, False, True, False, True, True, False, True, True, True, True, True, False, True, True, True, True, True, False, True, True, True, True, True, True, False, False, True, False, True, True, True, False, True, False, True, True, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, False, True, True, True, True, True, True, False, False, True, False, False, False, False, True, True, True, True, False, True, False, False, False, True, False, False, False, False, True, False, True, True, False, True, False, True, False, False, False, True, True, False, True, False, False, False, True, False, True, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, False, True, False, True, True, True, True, False, False, False, True, True, True, False, True, False, True, False, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, True, True, False, True, True, True, False, True, False, False, True, True, False, False, False, True, True, True, True, True, True, False, True, False, False, False, True, True, True, True, True, False, False, True, False, True, True, False, False, True, True, False, True, True, False, False, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, False, True, False, True, True, True, False, False, True, False, False, True, True, False, True, True, False, True, False, True, False, True, True, True, True, True, False, False, True, False, True, True, False, False, True, False, True, True, False, True, True, True, True, True, True, False, True, True, True, True, True, True, False, False, False, False, True, False, True, False, False, True, True, True, True, True, True, False, False, False, False, True, False, False, False, False, True, False, False, False, True, False, True, False, False, True, False, True, True, True, False, True, True, True, True, False, True, True, True, True, False, False, True, True, False, True, True, True, False, True, True, False, True, False, False, True, True, True, True, False, True, True, False, True, True, True, True, False, False, True, True, False, True, True, False, True, False, False, True, False, True, True, True, False, True, True, True, False, True, False, False, False, True, True, True, False, True, True, False, True, True, True, True, True, False, False, True, True, True, True, True, False, False, True, True, False, True, False, True, False, True, False, False, False, False, True, True, False, True, True, False, True, True, True, True, False, False, False, False, True, False, False, False, False, True, True, True, False, True, True, True, True, False, False, True, True, False, True, True, False, True, True, False, False, True, False, False, True, False, True, True, True, True, False, False, False, True, False, False, True, True, True, True, True, True, False, True, True, True, False, False, False, False, True, False, True, False, True, False, False, False, True, False, True, True, True, True, True, False, True, True, True, False, True, False, True, False, True, False, False, False, False, True, True, False, False, False, True, True, False, True, False, False, True, True, True, True, True, True, False, False, False, True, True, False, True, False, False, False, True, True, False, True, True, True, True, True, True, True, True, True, False, True, False, True, True, False, True, True, True, True, True, True, False, False, False, True, True, False, False, True, True, True, True, True, False, True, True, True, True, True, True, True, True, False, True, True, True, False, True, True, True, True, False, True, True, False, True, False, False, True, False, True, True, True, True, False, True, True, True, False, True, True, True, False, True, True, True, False, True, False, True, False, True, True, False, True, False, True, False, True, True, False, False, True, True, True, False, True, True, True, True, False, True, False, False, True, True, False, True, True, True, True, True, False, False, True, True, True, False, False, True, False, True, True, True, False, False, True, True, False, True, False, False, True, False, False, True, False, False, True, False, False, True, True, True, True, True, True, True, True, True, False, True, True, False, True, True, True, False, False, True, False, False, True, False, True, False, True, True, True, False, True, False, True, True, False, True, True, False, False, True, False, True, True, False, False, True, True, True, False, True, True, True, True, False, True, False, True, False, True, True, True, False, True, False, True, False, True, True, True, False, True, True, False, True, True, False, True, True, False, False, False, True, True, True, False, True, True, True, True, True, True, True, False, False, False, True, False, False, False, False, False, True, True, True, True, True, True, False, False, True, True, False, True, False, True, False, False, True, True, True, True, True, False, True, False, False, False, True, True, False, False, True, True, True, False, True, True, True, True, False, True, True, True, False, False, True, True, True, True, True, False, True, True, True, False, True, True, False, True, True, False, True, True, True, True, True, True, True, True, False, True, False, True, True, True, False, True, False, True, True, False, True, True, True, True, False, False, True, True, True, False, True, True, True, False, True, False, True, True, False, True, True, True, False, True, True, False, True, True, True, False, False, True, True, True, True, True, False, True, True, True, True, False, True, False, True, True, False, False, True, False, False, False, True, True, True, True, False, True, True, True, True, True, False, True, False, False, True, True, True, False, True, True, True, True, True, True, False, False, True, True, True, True, False, True, True, True, True, True, True, False, True, True, False, False, True, True, False, True, True, False, True, True, True, True, True, False, True, False, True, True, False, False, True, False, False, True, True, True, True, False, False, True, True, True, True, False, True, False, True, False, False, True, False, True, True, True, False, True, False, True, True, True, False, False, True, False, True, True, True, True, True, True, True, True, False, False, False, False, True, False, True, True, False, True, True, True, True, True, False, False, False, False, True, False, True, False, True, False, False, False, True, True, False, True, True, False, True, True, False, True, True, True, True, True, False, True, True, True, True, False, True, True, True, True, True, True, False, True, True, False, True, True, False, False, False, True, False, False, True, True, True, False, True, True, True, False, True, False, False, True, True, True, True, False, False, False, True, True, False, False, False, True, True, True, False, False, True, True, False, True, True, True, True, False, False, False, False, False, True, True, True, True, True, False, False, True, False, False, True, False, True, False, True, False, True, False, True, False, True, False, False, False, True, True, False, True, True, True, True, False, True, True, True, False, True, True, True, True, True, False, False, False, True, True, True, True, True, True, True, True, True, False, False, True, False, False, True, False, True, True, False, True, False, False, True, True, False, True, True, True, True, True, True, True, False, False, False, False, True, True, False, True, True, True, True, False, True, True, False, True, True, False, True, True, False, True, True, True, False, False, True, False, False, True, True, True, True, False, True, True, True, False, False, True, True, False, True, True, False, False, True, True, False, True, False, True, True, True, False, True, False, True, False, True, True, False, False, False, True, True, True, True, True, False, True, False, True, False, True, True, True, True, True, True, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True, False, False, False, True, False, True, True, True, False, False, True, False, True, False, True, True, False, False, True, False, True, False, True, False, True, False, False, True, True, False, True, True, True, True, True, False, True, False, False, True, True, False, True, False, True, True, False, True, False, False, False, True, False, False, True, True, True, False, False, True, False, True, True, True, False, False, True, False, False, True, True, False, True, False, True, False, False, True, True, True, True, True, True, False, True, True, False, True, True, True, True, True, False, True, True, False, False, True, False, True, False, True, True, True, True, False, False, True, True, False, False, True, True, True, False, False, False, True, False, False, True, True, False, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, False, False, True, True, True, True, True, False, True, True, False, True, True, True, False, True, True, False, False, True, False, True, False, True, False, False, True, True, False, True, False, False, True, True, True, False, True, True, False, False, True, True, False, False, False, True, True, False, True, True, True, False, True, False, True, True, True, True, True, False, True, True, False, False, True, False, True, False, True, True, True, True, False, True, True, True, False, False, True, False, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, False, False, False, False, True, False, True, False, True, True, True, False, False, True, True, True, True, False, False, True, False, True, True, True, True, True, True, False, True, True, False, True, False, False, False, False, True, True, True, True, False, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, False, True, True, False, True, 

Save it in a .csv file and submit it in the Kaggle competition.

The format is as follows:
1. First column is the original `PassengerId` column in the test set;
2. Second column is named `Transported` and contains the predictions (only 0's or 1's).

In [45]:
y_pred_temp=[]                                                                   
for each in y_pred:
  y_pred_temp.append(str(each).upper())                                         #fix for converting true/false to TRUE/FALSE for kaggle
y_pred=y_pred_temp

In [46]:
print(y_pred)

['FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 'TRUE', 'TR

In [47]:
df_id = df_test['PassengerId']
df_class = pd.DataFrame(data=y_pred, columns = ['Transported'])
df_pred = pd.concat([df_id, df_class], axis=1)

df_pred.to_csv('predictions_'+str(hof.items[0].fitness.values[0])+'.csv', sep=',', index=False)

In [48]:
from google.colab import files
files.download('predictions_'+str(hof.items[0].fitness.values[0])+'.csv')       #download the predictions with fitness score in name